### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by stapelberg** [google/renameio#1]
This package was developed/tested on Linux.

We should add windows-specific code which does the closest thing to the rename/fsync combination there is.

Contributions very welcome.

**Comment by mvdan** [comment]
FYI, Travis now has Windows support too: https://docs.travis-ci.com/user/reference/windows/

It's new though, so it might be a bit rough around the edges. But you should definitely have Mac and Windows on CI.

**Comment by stapelberg** [comment]
Thanks for the reference. I’m not sure it makes sense to add Windows to travis before we have any Windows-specific code, though?

**Comment by mvdan** [comment]
Of course - this was just an FYI, to add that once the project starts maintaining code just for Windows.

**Comment by natefinch** [comment]
I have some windows code that should be a good start for it.  You've fixed the bug I had of needing the file on the same filesystem to use move file - https://github.com/natefinch/atomic

**Comment by stapelberg** [comment]
Hey @natefinch, hope you are well!

Thanks for the link to the windows code. Would you prefer I go ahead and copy it, or would you prefer contributing the code as a Pull Request to retain proper attribution?

**Comment by natefinch** [comment]
PR incoming

**Comment by twpayne** [comment]
From our chat at the Zürich Go meetup last week, I understood that it is not possible to do atomic file replacement on Windows.

If this understanding is correct, could you close this issue as `CANTFIX`?

cc @zb140

**Comment by stapelberg** [comment]
Sure. I was referring to https://github.com/golang/go/issues/22397#issuecomment-498856679
