### ISSUE TITLE
Question: fsync on file and/or directory

### ISSUE THREAD

**Issue by nmeum** [google/renameio#11]
The README file states the following under subtleties which must be
consider when using `rename(3)` for atomic file writes:

	On POSIX operating systems, the `fsync` system call must be used
	to ensure that the `os.Rename()` call will not result in a
	0-length file.

And `tempfile.go` does indeed use `fsync(3)` through `File.Sync()` (from
the `os` package) in the `CloseAtomicallyReplace` function. This
performs an `fsync` for the underlying file descriptor of the **regular
PendingFile**.

I was, however, wondering if this is sufficient. Unfortunately, the
definition of `fsync` in POSIX.1-2008 seems very vague to me. The POSIX
specification of `fsync` states the following:

	The fsync() function shall request that all data for the open
	file descriptor named by fildes is to be transferred to the
	storage device associated with the file described by fildes.

But doesn't explicitly mentioned which data this applies to. For
instance, the name of the file is usually (not sure if POSIX mandates
this) not part of the file metadata (e.g. the inode) but instead stored
in the directory file.

The linux man page for `fsync` is more specific on this issue and states
the following:

	Calling fsync() does not necessarily ensure that the entry in
	the directory containing the file has also reached disk. For
	that an explicit fsync() on a file descriptor for the directory
	is also needed.

I would therefore assume that it is necessary to also **perform an
`fsync(3)` operation on the file descriptor for the directory
containing the file** (at least on Linux).

To further investigate this I looked at the [C implementation of an atomic
write][vis atomic write] in the text editor [vis][vis github] which seems to
perform an `fsync` operation on both: the directory containing the file
and the file itself.

I was wondering if this should also be implemented in renameio. If not:
The reasons for not doing so should be documented since this doesn't
seem obvious to me.

[vis github]: https://github.com/martanne/vis
[vis atomic write]: https://github.com/martanne/vis/blob/b3bec56d86f602da418763d3521aad87d5eb6b25/text.c#L901-L935

**Comment by stapelberg** [comment]
What’s currently implemented is enough for *atomicity*, not for *durability*. This is intentional: for applications which are idempotent, not flushing to disk is a performance win.

I’ll update the README to that extent when I get a chance, but feel free to race me to it with a PR, if you’d like :)

**Comment by nmeum** [comment]
> What’s currently implemented is enough for atomicity, not for durability. 

Just out of curiosity: Why is the `fsync` call on the regular file required for *atomicity* isn't *atomicity* already guaranteed by `rename(3)`? POSIX.1-2008 explicitly states that: `[This] specification requires that the action of the [rename] function be atomic.`

**Comment by stapelberg** [comment]
Please see https://github.com/google/renameio/blob/8bac8552c40822a27a77e2b2a7d2788c4d590d04/tempfile.go#L107-L114
