### ISSUE TITLE
[]byte vs io.Writer

### ISSUE THREAD

**Issue by philtay** [google/renameio#12]
There are many methods in the stdlib and in the wild that accept a `io.Writer` argument. A signature like `func Write(w io.Writer) error` is idiomatic.
Currently, the `WriteFile` function of this library accepts a `[]byte` slice. Basically the entire content of the file must be read in memory before writing it.
Are you open to add a function like the one below to solve this problem?

```Go
func Write(filename string, wr func(io.Writer) error, perm os.FileMode) error {
	t, err := TempFile("", filename)
	if err != nil {
		return err
	}
	defer t.Cleanup()

	if err := t.Chmod(perm); err != nil {
		return err
	}

	if err := wr(t); err != nil {
		return err
	}

	return t.CloseAtomicallyReplace()
}
```

**Comment by stapelberg** [comment]
WriteFile mirrors ioutil.WriteFile and is intended for small files indeed.

For writing larger files, use https://godoc.org/github.com/google/renameio#TempFile (which is what WriteFile uses under the hood).

**Comment by stapelberg** [comment]
I’ll close this issue, but please let me know if you have further questions.

**Comment by philtay** [comment]
Yes, I know. The fact is that `TempFile` is not a "real" `io.Writer`. In order to correctly use it you need the boilerplate code already present in `WriteFile`. You can't just pass a `TempFile` instance as an argument to a `Write` function and forget about it. What I'm talking about is a convenience function for large files that abstracts away the boilerplate that you must write every time you use a `TempFile`.

P.S. It would be great if you could tag a release. Thanks!
