### ISSUE TITLE
Request: tag new version

### ISSUE THREAD

**Issue by twpayne** [google/renameio#26]
There have been [a few updates since `v0.1.0` was tagged](https://github.com/google/renameio/compare/v0.1.0...master). Could you tag a new version please?

**Comment by stapelberg** [comment]
Could we add the helper package discussed in https://github.com/google/renameio/pull/20#issuecomment-689383206 first to finish the windows situation? I’d like to avoid users having to copy&paste elaborate fallback mechanisms in their code.

**Comment by twpayne** [comment]
With #27 merged, would it be possible to tag a new version? `0.2.0` or even `1.0.0` if you're feeling brave - the module has been quite stable for a while now.

**Comment by stapelberg** [comment]
Absolutely! Thanks for the reminder. `v1.0.0` tag now pushed. Let me know if anything needs changing.
