### ISSUE TITLE
maybe: doesn't build on Windows

### ISSUE THREAD

**Issue by ainar-g** [google/renameio#29]
The text of package `maybe` implies that it could run on Windows:

```go
if runtime.GOOS == "windows" {
        return ioutil.WriteFile(filename, data, perm)
}
return renameio.WriteFile(filename, data, perm)
```

But it wont, since `renameio.WriteFile` doesn't exist when building on Windows.  It should probably use build tags (and `go:build` directives) instead of `runtime.GOOS`.

**Comment by mvdan** [comment]
Perhaps release this as v1.0.1? I ran into build failures when upgrading to v1.0.0, and then I switched to /maybe, and then it still failed because of this bug :)

**Comment by stapelberg** [comment]
> Perhaps release this as v1.0.1

Now done
