### ISSUE TITLE
Add TempFile Directoy parameter to WriteFile

### ISSUE THREAD

**Issue by FF-AntiK** [google/renameio#32]
https://github.com/google/renameio/blob/370b856c87755ae99ae5f93f85f113b98f216cff/writefile.go#L24

`WriteFile` uses an empty string as the `TempFile` Directory. Please add this as parameter to `WriteFile`.

**Comment by stapelberg** [comment]
No: the renameio.WriteFile method is designed to use the same signature as ioutil.WriteFile.

Use the TempFile entry point directly if you have a need to specify the directory.

**Comment by FF-AntiK** [comment]
I understand, thanks!
