### ISSUE TITLE
fs.FS support?

### ISSUE THREAD

**Issue by ainar-g** [google/renameio#37]
Considering that the package is quite low-level at times, would it be at all possible to add support for the `fs.FS` interface?  For example, to have versions of `TempDir` and `TempFile` that accept `fs.FS`?  And perhaps the latter would return a modified version of `fs.File`?

**Comment by stapelberg** [comment]
I have only used `fs.FS` when working with the `embed` package thus far, so my experience with it is limited.

When you suggest adding a version of `TempFile` that accepts `fs.FS`, what sort of use-cases would that make possible? Can you provide an example or a specific motivation?

`renameio` needs `os.OpenFile` (to create a new file), `(*os.File).Sync` and `os.Rename`. AFAICT, `fs.FS` offers none of these, so we’d need to use interface assertions, or a custom interface to begin with.
