### ISSUE TITLE
Option to ignore TEMPDIR

### ISSUE THREAD

**Issue by adam-azarchs** [google/renameio#43]
There exist filesystems which do not correctly handle atomically renaming of files between different directories, even if they're on the same filesystem.  It's true that this is not POSIX-compliant behavior but we've seen it on customer systems, specifically with BeeGFS, likely due to the way they shard filesystem metadata between servers.  While respecting `TEMPDIR` is nice in general, it needs to be optional to deal with that sort of thing.

**Comment by stapelberg** [comment]
I don’t understand what the POSIX-violating rename behavior has to do with honoring TMPDIR. Can you explain?

Either way, the https://pkg.go.dev/github.com/google/renameio/v2#WithTempDir option already exists. Doesn’t that work for you?

**Comment by adam-azarchs** [comment]
On some of these not-quite-POSIX-compliant network filesystems, renames are atomic if you aren't renaming between directories.  So, `mv /dir/foo.tmp /dir/foo` is atomic, but `mv /tmp/foo.tmp /dir/foo` is not, even if they are on the same filesystem.  If `WithTempDir` is not provided, it defaults to `TempDir(dest)`, which will use `os.TempDir()` if that is on the same filesystem, on the (generally reasonable) assumption that if it's on the same filesystem then it is safe to use.  The problem is that in cases like this, being on the same filesystem is insufficient.  Using `WithTempDir(path.Dir(dest))` works, but is a bit inconvenient to put everywhere if one needs to be robust against that kind of behavior.

**Comment by stapelberg** [comment]
Thanks for the explanation.

> Using `WithTempDir(path.Dir(dest))` works, but is a bit inconvenient to put everywhere if one needs to be robust against that kind of behavior.

…but that is the only options mechanism that we have in the renameio package. 

Are you asking to introduce a process-global behavior change? I’m not sure that’s justified for such a niche use-case.

**Comment by adam-azarchs** [comment]
Yes, I suppose you're right.  Closing this issue.
