### ISSUE TITLE
TempDir can return an unusable directory

### ISSUE THREAD

**Issue by twpayne** [google/renameio#8]
The documentation for `renameio.TempDir` states:

> TempDir checks whether os.TempDir() can be used as a temporary directory for later atomically replacing files within dest.

On macOS, `renameio.TempDir` can return an unusable temporary directory. For example, my home directory is `/Users/twp`, and calling `renameio.TempDir("/Users/twp")` returns `"/Users"`, which I do not have permission to write to. I haven't tested on other operating systems.

This program, adapted from the Many Example demonstrates the problem:

```go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/renameio"
)

func run() error {
	homeDir := os.Getenv("HOME")
	dir := renameio.TempDir(homeDir)
	t, err := renameio.TempFile(dir, filepath.Join(homeDir, "hello.txt"))
	if err != nil {
		return err
	}
	defer t.Cleanup()
	if _, err := t.Write([]byte("Hello, world!\n")); err != nil {
		return err
	}
	return t.CloseAtomicallyReplace()
}

func main() {
	if err := run(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

Running this on my system yields:

```
$ go run main.go
open /Users/.hello.txt549952214: permission denied
exit status 1
```

Note that `renameio.WriteFile` works fine - likely because the temporary directory is computed for the single file being written, rather than using a cached value for many writes to the same directory.

**Comment by stapelberg** [comment]
Thanks for the report. I think I got confused with regards to filepath.Dir — that call should not happen in tempDir(). Let me push a fix.

**Comment by stapelberg** [comment]
Should be fixed. Can you confirm?

**Comment by twpayne** [comment]
Confirmed, thanks for the super-quick fix!
